import { ThemeProvider } from "@/theme/ThemeProvider";
import { ServerThemeProvider } from "@wits/next-themes";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ServerThemeProvider>
      <html lang="en">
        <body className={clsx(inter.className, "bg-background")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            enableColorScheme
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
